name: PR Review
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
        
      - name: AI Code Review
        uses: amitwa1/pr-reviewer@v1
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          ai_provider: 'azure'
          model: 'gpt-4o-mini'
          azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          review_level: 'standard'
          comment_style: 'both'
          inline_severity: 'warning'
          summary_format: 'detailed'
          request_delay: '2000'
