name: PR Review
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number'
        required: true
        type: string
  issue_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    # Only run if manually triggered or if comment contains '/review'
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && github.event.issue.pull_request != null && contains(github.event.comment.body, '/review'))
    permissions:
      contents: read
      pull-requests: write
      issues: write
      actions: read
    steps:
      - name: Debug event info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Comment body: ${{ github.event.comment.body }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Is PR: ${{ github.event.issue.pull_request != null }}"
          
      - name: Get PR details
        id: pr_details
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "pr_number=${{ github.event.inputs.pr_number }}" >> $GITHUB_OUTPUT
          else
            echo "pr_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: refs/pull/${{ steps.pr_details.outputs.pr_number }}/head
        
      - name: AI Code Review
        uses: amitwa1/pr-reviewer@v1
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          pr_number: ${{ steps.pr_details.outputs.pr_number }}
          ai_provider: 'azure'
          model: 'gpt-4o-mini-amit'
          azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          review_level: 'standard'
          comment_style: 'both'
          inline_severity: 'warning'
          summary_format: 'detailed'
          request_delay: '1000'
