name: PR Review
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  pull_request_target:
    types: [opened, synchronize, ready_for_review]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        
      - name: AI Code Review
        uses: amit.wagner/pr-reviewer@v1
        with:
          github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          review_level: 'standard'
          comment_style: 'both'
          inline_severity: 'warning'
          summary_format: 'detailed'
